apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-main
spec:
  selector:
    matchLabels:
      app: controller-main
  replicas: 1
  template:
    metadata:
      labels:
        app: controller-main
    spec:
      serviceAccountName: workflow
      containers:
        - name: controller-main
          image: ktmrgk/sample-controller:latest